#!/bin/bash

function usage
{
	echo "Usage: $0 <profile>"
}

if [ `id -u` != "0" ]; then
	echo "Error: this script must be run as root."
	exit 1
fi

if (( $# < 1)); then
	usage
	exit 1
fi

if [ ! -e "/etc/n2n/$1" ]; then
	echo "Error: could not open profile definition in /etc/n2n/$1"
	exit 1
fi

INTF_NAME=n2n-$1

. /etc/n2n/$1

if [ ! -n "${INTF_ADDRESS+x}" ]; then
	echo "Error: interface address not set."
	exit 1
fi

if [ ! -n "${INTF_MASK+x}" ]; then
	echo "Error: interface subnet mask not set."
	exit 1
fi

if [ ! -n "${NETWORK_NAME+x}" ]; then
	echo "Error: Network community name not set."
	exit 1
fi

if [ ! -n "${N2N_KEY+x}" ]; then
	echo "Error: Network key not set."
	exit 1
fi

if [ ! -n "${SUPERNODE_ADDRESS+x}" ]; then
	echo "Error: Supernode address not set."
	exit 1
fi

if [ -n "${N2N_UID+x}" -a -n "${N2N_GID+x}" ]; then
	PRIV_PART="-u $N2N_UID -g $N2N_GID"
else
	PRIV_PART=""
fi

N2N_KEY=$N2N_KEY edge -d $INTF_NAME -a $INTF_ADDRESS -s $INTF_MASK -c $NETWORK_NAME -l $SUPERNODE_ADDRESS $PRIV_PART -b -f
