#!/bin/sh

function usage
{
	echo "Usage: $0 <profile>"
}

if [ `id -u` != "0" ]; then
	echo "Error: this script must be run as root."
	exit 1
fi

if (( $# < 1)); then
	usage
	exit 1
fi

if [ ! -e "/etc/n2n/$1" ]; then
	echo "Error: could not open profile definition in /etc/n2n/$1"
	exit 1
fi

. /etc/n2n/$1

if [ ! -z $INTF_ADDRESS ]; then
	echo "Error: interface address not set."
	exit 1
fi

if [ ! -z $NETWORK_NAME ]; then
	echo "Error: Network community name not set."
	exit 1
fi

if [ ! -z $N2N_KEY ]; then
	echo "Error: Network key not set."
	exit 1
fi

if [ ! -z $SUPERNODE_ADDRESS ]; then
	echo "Error: Supernode address not set."
	exit 1
fi

/usr/sbin/edge -a $INTF_ADDRESS -c $NETWORK_NAME -k $N2N_KEY -l $SUPERNODE_ADDRESS -f
